feat: test3

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -23,8 +23,42 @@ permissions:
 
 
 jobs:
+
+  check_version:
+    name: "Check if Release Exists"
+    runs-on: ubuntu-latest
+    outputs:
+      should_run: ${{ steps.check.outputs.should_run }}
+    steps:
+      - name: Checkout (minimal)
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Check version availability
+        id: check
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          VERSION="${{ inputs.version || github.ref_name }}"
+          # Check if release exists
+          if gh release view "$VERSION" >/dev/null 2>&1; then
+            if [ "${{ inputs.force }}" = "true" ]; then
+              echo "Release $VERSION exists but 'force' is true. Proceeding..."
+              echo "should_run=true" >> $GITHUB_OUTPUT
+            else
+              echo "::error::Release $VERSION already exists. Stopping to save build minutes."
+              echo "should_run=false" >> $GITHUB_OUTPUT
+              exit 1 # This stops the whole workflow immediately
+            fi
+          else
+            echo "should_run=true" >> $GITHUB_OUTPUT
+          fi
+
   build:
     name: Build (${{ matrix.os }})
+    needs: [check_version]
+    if: needs.check_version.outputs.should_run == 'true'
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
@@ -71,8 +105,8 @@ jobs:
 
   release:
     name: Create Release
+    needs: [build] 
     runs-on: ubuntu-latest
-    needs:  build 
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -93,7 +127,7 @@ jobs:
             echo "::error::Release $VERSION already exists. Use 'force' input to overwrite."
             exit 1 # Stops the job immediately if it exists and force is false
           fi
-          
+
       - name: Download All Artifacts
         uses: actions/download-artifact@v4
         with:
